import { useState } from 'react'
import { ArrowRight, CheckCircle2, Factory, Facebook, Instagram, Linkedin, Mail, MapPin, Menu, MessageSquare, Phone, ShieldCheck, Truck, X } from 'lucide-react'

const products = [
  { name: 'Standard Portland Cement', code: 'CPC-43', text: 'Reliable general-purpose cement for residential and commercial construction.', tags: ['Consistent', 'Versatile'] },
  { name: 'Premium OPC Cement', code: 'OPC-53', text: 'Higher early strength for demanding structural and infrastructure applications.', tags: ['High strength', 'Fast setting'] },
  { name: 'Premium Quality Cement', code: 'PQC-Plus', text: 'Performance-focused cement for durable foundations and long-life builds.', tags: ['Durable', 'Performance'] },
]
const services = [
  [Factory, 'Quality Products', 'Cement products selected for consistent performance and dependable results.'],
  [Truck, 'Timely Delivery', 'Planned dispatch and delivery support for projects of different sizes.'],
  [MessageSquare, 'Customer Support', 'Clear communication from enquiry through product and supply discussions.'],
  [ShieldCheck, 'Build Supply', 'A straightforward supply experience designed around contractors and customers.'],
]
const nav = [['Home','home'],['About','about'],['Products','products'],['Services','services'],['Inquiry','inquiry'],['Contact','contact']]
function BrandMark(){return <span className="brand-mark" aria-hidden="true"><i/><b/></span>}
function CementBag({small=false}){return <div className={`cement-bag ${small?'small':''}`}><span className="bag-top"/><BrandMark/><strong>CHANDANSHIV</strong><small>CEMENT PRODUCTS</small><em/></div>}
function Header({open,setOpen}){return <header className="header"><a className="logo" href="#home"><BrandMark/><span><b>CHANDANSHIV</b><small>CEMENT PRODUCTS</small></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button><nav className={open?'nav open':'nav'}>{nav.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{label}</a>)}<a className="nav-cta" href="#inquiry" onClick={()=>setOpen(false)}>Get a Quote <ArrowRight size={15}/></a></nav></header>}
function Hero(){return <section id="home" className="hero"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow">Trusted cement supply for stronger builds</div><h1>Stronger Foundations,<br/><span>Better Tomorrow.</span></h1><p>Reliable cement products and responsive service for homes, commercial projects, infrastructure and everything built to last.</p><div className="actions"><a className="btn primary" href="#products">Explore Products <ArrowRight/></a><a className="btn ghost" href="#inquiry">Send an Inquiry</a></div><div className="proof"><span><CheckCircle2/> Quality-focused supply</span><span><CheckCircle2/> Responsive support</span><span><CheckCircle2/> Delivery coordination</span></div></div><div className="hero-art"><div className="sun"/><div className="floor"/><div className="hero-bag"><CementBag/></div><div className="hero-bag second"><CementBag small/></div></div></section>}
function Stats(){return <section className="stats"><div><strong>24/7</strong><span>Access to business information</span></div><div><strong>3+</strong><span>Product categories showcased</span></div><div><strong>100%</strong><span>Responsive across devices</span></div><div><strong>1:1</strong><span>Customer-focused communication</span></div></section>}
function About(){return <section id="about" className="section about"><div className="label">01 — About us</div><div className="two-col"><div><h2>A dependable digital front door for a <span>stronger business.</span></h2><p className="lead">Chandanshiv Cement Products is presented here as a modern, accessible business platform that makes products, services and contact information easy to discover.</p><p>The experience is designed to build trust quickly: clear product information, straightforward service details, prominent enquiry paths and a mobile-first interface keep the customer journey simple.</p></div><div className="about-card"><Factory size={28}/><span>Business focus</span><h3>Build confidence before the first conversation.</h3><ul>{['Professional online presence','Clear product showcase','Fast enquiry access','Responsive user experience'].map(x=><li key={x}><CheckCircle2/> {x}</li>)}</ul></div></div></section>}
function Products(){const [selected,setSelected]=useState(null);return <section id="products" className="section products"><div className="heading"><div><div className="label">02 — Products</div><h2>Materials for <span>solid progress.</span></h2></div><p>Explore the featured range. Exact specifications, pack sizes and certifications can be added once verified.</p></div><div className="product-grid">{products.map((p,i)=><article className="product" key={p.code}><div className="product-visual"><CementBag/></div><div className="product-body"><span className="code">{p.code}</span><h3>{p.name}</h3><p>{p.text}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><button onClick={()=>setSelected(p)}>Ask about this product <ArrowRight size={15}/></button></div></article>)}</div>{selected&&<div className="modal" onClick={e=>e.target===e.currentTarget&&setSelected(null)}><div className="modal-card"><button className="close" onClick={()=>setSelected(null)}><X/></button><CementBag/><div><span className="code">{selected.code}</span><h2>{selected.name}</h2><p>{selected.text}</p><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><a className="btn dark" href="#inquiry" onClick={()=>setSelected(null)}>Send an Inquiry <ArrowRight/></a></div></div></div>}</section>}
function Services(){return <section id="services" className="section services"><div className="label">03 — Services</div><div className="heading"><h2>Simple service. <span>Serious support.</span></h2><p>Everything around the product should feel as dependable as the product itself.</p></div><div className="service-grid">{services.map(([Icon,title,text],i)=><article key={title}><span className="num">0{i+1}</span><div className="icon"><Icon/></div><h3>{title}</h3><p>{text}</p><ArrowRight className="service-arrow"/></article>)}</div></section>}
function Inquiry(){const [sent,setSent]=useState(false);return <section id="inquiry" className="section inquiry"><div className="inquiry-copy"><div className="label light">04 — Inquiry</div><h2>Tell us what you're <span>building.</span></h2><p>Use this enquiry entry point for product, supply and project conversations. Connect a backend or email service when real submissions are required.</p><div className="inquiry-points"><span><Phone/> Direct follow-up</span><span><MessageSquare/> Clear requirements</span><span><CheckCircle2/> Fast response workflow</span></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent&&<div className="success"><CheckCircle2/> Demo enquiry captured.</div>}<label>Name<input required placeholder="Your full name"/></label><div className="form-row"><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Phone<input inputMode="tel" placeholder="+91 ..."/></label></div><label>Product / Requirement<select defaultValue=""><option value="" disabled>Select a requirement</option>{products.map(p=><option key={p.code}>{p.name}</option>)}<option>General business enquiry</option></select></label><label>Message<textarea required rows="4" placeholder="Tell us about your project or requirement..."/></label><button className="btn dark full">Send Inquiry <ArrowRight/></button></form></section>}
function Contact(){return <section id="contact" className="section contact"><div><div className="label">05 — Contact</div><h2>Let's make the next <span>build stronger.</span></h2><p className="lead">Replace the sample details below with the company's verified address, phone, email and social links before publishing.</p></div><div className="contact-grid"><a href="tel:+919999999999"><Phone/><span>Phone</span><strong>+91 99999 99999</strong><small>Call for product & supply enquiries</small></a><a href="mailto:info@chandanshivcement.com"><Mail/><span>Email</span><strong>info@chandanshivcement.com</strong><small>Send a requirement or question</small></a><div><MapPin/><span>Address</span><strong>Someshwar, Maharashtra</strong><small>Replace with verified business address</small></div></div></section>}
function Footer(){return <footer><div><a className="logo" href="#home"><BrandMark/><span><b>CHANDANSHIV</b><small>CEMENT PRODUCTS</small></span></a><p>Stronger foundations, better tomorrow.</p></div><div className="footer-links"><b>Explore</b>{nav.slice(0,5).map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</div><div className="social"><a href="#contact" aria-label="Facebook"><Facebook/></a><a href="#contact" aria-label="Instagram"><Instagram/></a><a href="#contact" aria-label="LinkedIn"><Linkedin/></a></div><div className="footer-bottom">© {new Date().getFullYear()} Chandanshiv Cement Products · Built with React + Vite</div></footer>}
export default function App(){const [open,setOpen]=useState(false);return <><Header open={open} setOpen={setOpen}/><main><Hero/><Stats/><About/><Products/><Services/><Inquiry/><Contact/></main><Footer/></>}
